version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data2:/var/lib/postgresql/data/
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
    volumes:
      - pgadmin_data2:/var/lib/pgadmin/

  app:
    container_name: app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: bash -c"python manage.py makemigrations user && python manage.py migrate && python manage.py runserver"
    # command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - app:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  postgres_data2:
  pgadmin_data2:
  app:
